apiVersion: v1
kind: Service
metadata:
  name: cortex-api-service
spec:
  selector:  # to connect to Pod through label
    app: cortex-api
  ports:
    - port: 80  # service port
      name: http-web
      protocol: TCP
      targetPort: http  # container port
