apiVersion: v1
kind: Secret
metadata:
  name: cortex-api-secret
  labels:
    sha: {{.Values.cortex_app.deploy.sha}}
type: Opaque
data:
  # cat cortex-cli/License.lic | base64 (on Mac)
  License.lic: {{ .Values.cortex_app.licenseLic }}
