apiVersion: v1
kind: Service
metadata:
  name: cortex-ui-service
  labels:
    sha: {{.Values.cortex_app.deploy.sha}}
spec:
  selector:  # to connect to Pod through label
    app: cortex-ui
  ports:
    - port: 80  # service port
      name: http-web
      protocol: TCP
      targetPort: http  # container port