apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-ui-configmap
  labels:
    sha: {{.Values.cortex_app.deploy.sha}}
data:
  nginx.conf: |
    server {
      listen       80;
      server_name  localhost;

      location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html =404;
      }
    }
  auth-config.json: |
    {
      "issuer": "{{.Values.cortex_app.OIDC_ISSUER_URL}}",
      "clientId": "{{.Values.cortex_app.CLIENT_ID}}",
      "identityService": "https://login.cortextest.cortexanalytics.com"
    }