apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: user-pool
spec:
  jwtRules:
    - issuer: {{.Values.cortex_app.OIDC_ISSUER_URL}}  # $OIDC_ISSUER_URL
      jwksUri: {{.Values.cortex_app.OIDC_JWKS_URI}}  # $OIDC_JWKS_URI
      forwardOriginalToken: true
      outputPayloadToHeader: x-jwt-trusted-payload
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: user-pool-app-public-client
spec:
  rules:
    - when:
        - key: request.auth.claims[iss]
          values:
            - {{.Values.cortex_app.OIDC_ISSUER_URL}}  # $OIDC_ISSUER_URL
