apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-qm-env-vars-configmap
  labels:
    sha: {{.Values.cortex_app.deploy.sha}}
data:
  DB_TYPE: {{.Values.cortex_app.env.DB_TYPE}}
  DB_USER: {{.Values.cortex_app.env.DB_USER}}
  DB_PASSWORD: {{.Values.cortex_app.env.DB_PASSWORD}}
  DB_NAME: {{.Values.cortex_app.env.DB_NAME}}
  DB_HOST: {{.Values.cortex_app.env.DB_HOST}}
  DB_PORT: {{.Values.cortex_app.env.DB_PORT | quote}}
