cortex_app:
  deploy:
    sha: "sha1"

  lisenceLic: ""

  image:
    camunda:
      repository: "249111255442.dkr.ecr.eu-central-1.amazonaws.com/cortex-camunda:7.15.14"
    cortex_cli:
      repository: "249111255442.dkr.ecr.eu-central-1.amazonaws.com/cortex-cli:1.4.18"
      pullPolicy: Always

  env:
    ConnectionStrings__BaseClientConnection: ""
    ConnectionStrings__MasterConnection: ""
    ConnectionStrings__DeploymentConnection: ""
    ConnectionStrings__AdminConnection: ""

  camunda:
    spring_profiles_active: sqlserver
    datasource_url: ""
    datasource_username: ""
    datasource_password: ""
    cortex_cli_sysscan_cron_schedule: ""
    replicas: 1
