# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - cortex=https://helm-charts.cortexanalytics.com/
helm-extra-args: --timeout 600s
