cortex_app:
  deploy:
    sha: "sha1"

  licenseLic: ""

  dnsZone: ""

  OIDC_ISSUER_URL: ""
  OIDC_JWKS_URI: ""
  CLIENT_ID: ""

  image:
    cortex_admin:
      repository: "249111255442.dkr.ecr.eu-central-1.amazonaws.com/cortex-admin:2.4.25"
    cortex_qm:
      repository: "249111255442.dkr.ecr.eu-central-1.amazonaws.com/cortex-qm:2.2.11"
    cortex_ui:
      repository: "249111255442.dkr.ecr.eu-central-1.amazonaws.com/cortex-ui:2.0.21"

  env:

    ASPNETCORE_ENVIRONMENT: "Production"
    ConnectionStrings__BaseClientConnection: ""
    ConnectionStrings__MasterConnection: ""
    ConnectionStrings__DeploymentConnection: ""
    ConnectionStrings__AdminConnection: ""
    Camunda__CamundaService: "http://camunda-service.camunda.svc.cluster.local:8080"

    DB_TYPE: "mssql"
    DB_USER: ""
    DB_PASSWORD: ""
    DB_NAME: ""
    DB_HOST: ""
    DB_IP_A: ""  # for debugging purpose only
    DB_PORT: 1433
    Cognito__region: ""
    Cognito__userPoolId: ""
    Cognito__appClientId: ""
