cortex_app:
  deploy:
    sha: "sha1"

  lisenceLic: ""

  dnsZone: ""

  OIDC_ISSUER_URL: ""
  OIDC_JWKS_URI: ""
  OAUTH2_PROXY_CLIENT_ID: ""

  image:
    camunda:
      repository: "249111255442.dkr.ecr.eu-central-1.amazonaws.com/cortex-camunda:7.15.14"
    cortex_cli:
      repository: "249111255442.dkr.ecr.eu-central-1.amazonaws.com/cortex-cli:1.3.93"
      pullPolicy: Always
    cortex_admin:
      repository: "249111255442.dkr.ecr.eu-central-1.amazonaws.com/cortex-admin:2.3.189"
    cortex_api:
      repository: "249111255442.dkr.ecr.eu-central-1.amazonaws.com/cortex-api:1.3.2"
    cortex_qm:
      repository: "249111255442.dkr.ecr.eu-central-1.amazonaws.com/cortex-qm:2.2.11"
    cortex_ui:
      repository: "249111255442.dkr.ecr.eu-central-1.amazonaws.com/cortex-ui:1.2.342"

  env:

    ASPNETCORE_ENVIRONMENT: "Production"
    ConnectionStrings__BaseClientConnection: ""
    ConnectionStrings__MasterConnection: ""
    ConnectionStrings__DeploymentConnection: ""
    ConnectionStrings__AdminConnection: ""
    Camunda__CamundaService: "http://camunda-service.camunda.svc.cluster.local:8080"

    DB_TYPE: "mssql"
    DB_USER: ""
    DB_PASSWORD: ""
    DB_NAME: ""
    DB_HOST: ""
    DB_IP_A: ""  # for debugging purpose only
    DB_PORT: 1433
    Cognito__region: ""
    Cognito__userPoolId: ""
    Cognito__appClientId: ""